name: update

on:
  # Content update
  push:
    paths:
      - '**.go'
      - '**.tmpl'
  # Daily update
  schedule:
    - cron: "0 0 * * *"   # At 00:00
  # Manual
  workflow_dispatch:

jobs:
  update:
    name: Updating repository information
    runs-on: ubuntu-latest
    container: golang:latest
    environment: production
    permissions:
      contents: write
    env:
      USER_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
    steps:
      # step1
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # step2
      - name: Get dependencies
        run: go get -v -t ./...

      # step3
      - name: Run script
        run: go run .
        continue-on-error: false

      # step4
      - name: Commit and push files
        if: ${{ success() }}
        run: |
          git config --global user.name "github-action-bot"
          git config --global user.email "github-action-bot@users.noreply.github.com"
          git add . && git commit -m "Update statistics"
          git push origin main        
      