name: update-content

on:
  # Content update
  push:
    paths:
      - '**.go'
      - '**.tmpl'
  # Daily update
  schedule:
    - cron: "0 0 * * *"   # At 00:00
  # Manual
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: false
jobs:
  # Build job
  build:
    name: Update repository statistics
    runs-on: ubuntu-latest
    container: golang:latest
    environment: production
    permissions:
      contents: write
      pages: write
    env:
      USER_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
    outputs: 
      status: ${{job.status}}      
    steps:  
      # step1
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # step2
      - name: Get dependencies
        run: go get -v -t ./...

      # step3
      - name: Run script
        run: go run .

      # step4
      - name: Commit and push files
        if: ${{ success() }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name "github-action-bot"
          git config --global user.email "github-action-bot@users.noreply.github.com"
          git add . && git commit -m "Update statistics"
          git push origin main   
        
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    if: ${{ needs.build.outputs.status == 'success' }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action